name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up JDK
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    # Build with Maven
    - name: Build with Maven
      run: mvn clean compile

    # Run Tests
    - name: Run tests
      run: mvn test

    # Package Application
    - name: Package application
      run: mvn package
